site_name: My Docs
theme:
  name: material
  language: 'ja'
  feature:
    tabs: true
extra_css:
    - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "css/custom.css"
extra:
    search:
        language: 'jp'
    font:
        text: "Noto Sans JP"
        code: "Consolas"




